name: Make on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build
      working-directory: tools
      run: make

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc
        DEST_NAME: qoi_enc_linux

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build
      working-directory: tools
      run: make

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc
        DEST_NAME: qoi_enc_macos

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build
      working-directory: tools
      shell: bash
      run: make

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc.exe
        DEST_NAME: qoi_enc_windows
        